version: '2'
services:
  jenkins:
    image: jenkins/jenkins
    volumes:
      -  /home/leo/jenkins:/var/jenkins_home
    ports:
      -   "8080:8080"
      -   "50000:50000"
    depends_on:
      - socat
    restart: always
    networks: 
      - jenkins_net
  socat:
    image: bpack/socat
    command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    expose:
        - "2375"
    networks: 
      - jenkins_net               
networks:
    jenkins_net:
    
